export const data = [
  {
    pageProps: {
      user: {
        id: 0,
        loginId: null,
        nickName: null,
        doctorId: 0,
        sex: null,
        profileImage: null,
        level: 0,
        birthYear: 0,
        country: null,
        myHospitalDistrict: {},
        districts: [],
        phoneNational: null,
        agreeEmail: false,
        agreeMarketing: false,
        agreeSms: false,
        sendPushAd: false,
      },
      authorization: "fd5ec22e099a45c0a9894c2e4e22007d",
      keyword: "코성형",
      treatmentCategoryName: "코성형",
      treatmentCategoryId: 412,
      breadcrumb: [
        {
          text: "홈",
          href: "/",
        },
        {
          text: "코성형",
          href: "/search?category=코성형",
        },
      ],
      totalLength: 23442,
      eventTotalLength: 3182,
      communityDocumentTotalLength: 10000,
      hospitalTotalLength: 260,
      treatmentTotalLength: 0,
      reviewTotalLength: 10000,
      reviews: [],
      events: [
        {
          id: 11780,
          title: "나나 코성형",
          titleImage:
            "https://image2.gnsister.com/images/direct/1715320859415_a3979353d36949df81f0a5e7d0494b73.jpg?originalImageWidth=1080&originalImageHeight=1080",
          treatmentList: [
            "비중격만곡증수술",
            "코재수술",
            "콧대(자가조직)",
            "콧대(보형물)",
            "코끝(보형물)",
            "코끝(자가연골)",
          ],
          hospitalId: 938,
          hospitalSubwayCode: "SUB_S9_925,SUB_S7_732",
          hospitalSubway: "신논현역",
          hospitalName: "나나성형외과의원",
          discountedCost: 1090000,
          cost: 1090000,
          currency: "KRW",
          discountRate: 0,
          rating: 9.7,
          ratingCount: 2909,
          type: "EVENT",
          vat: "INCLUDED",
          createTime: 1583972634000,
          assessmentState: "GROWTH",
          useBuyNow: false,
        },
        {
          id: 14274,
          title: "에이비_자려한코성형",
          titleImage:
            "https://image2.gnsister.com/images/direct/1694065890103_34f4a814753043938b011e85a8c1cf99.jpg?originalImageWidth=1080&originalImageHeight=1080",
          treatmentList: [
            "비중격만곡증수술",
            "코재수술",
            "콧대(자가조직)",
            "콧대(보형물)",
            "코끝(보형물)",
            "코끝(자가연골)",
            "비밸브협착증수술",
            "비후성비염수술",
          ],
          hospitalId: 3004,
          hospitalSubwayCode: "SUB_S2_222,SUB_S9_925",
          hospitalSubway: "강남역",
          hospitalName: "에이비성형외과의원",
          discountedCost: 1839000,
          cost: 3670000,
          currency: "KRW",
          discountRate: 50,
          rating: 9.4,
          ratingCount: 1400,
          type: "EVENT",
          vat: "INCLUDED",
          createTime: 1600813655000,
          assessmentState: "CERTIFIED",
          useBuyNow: false,
        },
        {
          id: 48314,
          title: "제스타 코성형",
          titleImage:
            "https://image2.gnsister.com/images/direct/1679981383061_4f05e4fcccba45ecab3e2dfd47335cb7.jpg?originalImageWidth=1080&originalImageHeight=1080",
          treatmentList: [
            "콧대(자가조직)",
            "콧대(보형물)",
            "코끝(보형물)",
            "코끝(자가연골)",
          ],
          hospitalId: 352,
          hospitalSubwayCode: "SUB_S3_336,SUB_S3_337,SUB_B_1512",
          hospitalSubway: "압구정역",
          hospitalName: "제스타성형외과",
          discountedCost: 1870000,
          cost: 1870000,
          currency: "KRW",
          discountRate: 0,
          rating: 10,
          ratingCount: 167,
          type: "EVENT",
          vat: "INCLUDED",
          createTime: 1679954474000,
          assessmentState: "CERTIFIED",
          useBuyNow: false,
        },
        {
          id: 3853,
          title: "예쁘면 DA야 자려한 코성형",
          titleImage:
            "https://image2.gnsister.com/images/direct/1701825136654_ffef052c3ee64964aaff5ffe76fa19d5.jpg?originalImageWidth=1080&originalImageHeight=1080",
          treatmentList: [
            "코재수술",
            "콧대(자가조직)",
            "콧볼축소",
            "콧대(보형물)",
            "코끝(보형물)",
            "코절골술",
            "비밸브협착증수술",
            "비후성비염수술",
          ],
          hospitalId: 250,
          hospitalSubwayCode: "SUB_S2_221,SUB_S2_222,SUB_JP_A_IY_10",
          hospitalSubway: "역삼역",
          hospitalName: "디에이성형외과의원",
          discountedCost: 1089000,
          cost: 1089000,
          currency: "KRW",
          discountRate: 0,
          rating: 9.4,
          ratingCount: 2115,
          type: "EVENT",
          vat: "INCLUDED",
          createTime: 1514328634000,
          assessmentState: "GROWTH",
          useBuyNow: false,
        },
        {
          id: 11938,
          title: "그랜드 자려한 코성형",
          titleImage:
            "https://image2.gnsister.com/images/direct/1712837211717_16c72c74c13f40d596f836a27a2f6603.jpg?originalImageWidth=1080&originalImageHeight=1080",
          treatmentList: ["콧대(자가조직)", "코끝(자가연골)"],
          hospitalId: 62,
          hospitalSubwayCode: "SUB_S3_336",
          hospitalSubway: "압구정역",
          hospitalName: "그랜드성형외과",
          discountedCost: 1539000,
          cost: 2750000,
          currency: "KRW",
          discountRate: 44,
          rating: 9.8,
          ratingCount: 266,
          type: "EVENT",
          vat: "INCLUDED",
          createTime: 1585270343000,
          assessmentState: "CERTIFIED",
          useBuyNow: false,
        },
        {
          id: 14169,
          title: "더도어_첫 코성형",
          titleImage:
            "https://image2.gnsister.com/images/direct/1695722450023_3dcfbff70f88409fa87b3860bc457461.jpg?originalImageWidth=1080&originalImageHeight=1080",
          treatmentList: [
            "코끝(기증연골)",
            "콧대(자가조직)",
            "콧볼축소",
            "콧대(보형물)",
            "코끝(보형물)",
            "코절골술",
            "코끝(자가연골)",
            "복코교정(수술)",
          ],
          hospitalId: 2783,
          hospitalSubwayCode: "SUB_S2_222",
          hospitalSubway: "강남역",
          hospitalName: "더도어성형외과",
          discountedCost: 1630000,
          cost: 1630000,
          currency: "KRW",
          discountRate: 0,
          rating: 9.7,
          ratingCount: 505,
          type: "EVENT",
          vat: "INCLUDED",
          createTime: 1600037627000,
          assessmentState: "CERTIFIED",
          useBuyNow: false,
        },
      ],
      communityDocuments: [
        {
          id: 2718045,
          categoryId: 2,
          categoryName: "시술/수술 전 질문",
          writer: {
            id: 6226568,
            doctorId: null,
            profile:
              "https://image2.gnsister.com/images/member/profile/1513135488959_68621d6a456f49a395a722609326fda4.png",
            nickname: "pinkgeek",
            level: 1,
            engagementType: null,
          },
          writerDoctorId: null,
          hasThumbUp: false,
          commentCount: 2,
          thumbUpCount: 0,
          viewCount: 0,
          createTime: "약 1시간 전",
          edited: true,
          title: "",
          contents:
            "별도의 진료소에서 하루 만에 안검하수/eyelid 수술 및 코 성형 수술이 가능한가요? 그 이유는 전문 분야도 다르고 첫번째 눈, 두번째 코 클리닉이 더 편하기 때문이다.",
          photos: [],
          lang: "en",
          hasDoctorComment: true,
          translateResult: null,
        },
        {
          id: 2718080,
          categoryId: 11,
          categoryName: "병원질문",
          writer: {
            id: 5942479,
            doctorId: null,
            profile:
              "https://image2.gnsister.com/images/member/profile/1513135488959_65b26532ee494877a051aff19efdb4cf.png",
            nickname: "소세징맛있어",
            level: 2,
            engagementType: null,
          },
          writerDoctorId: null,
          hasThumbUp: false,
          commentCount: 1,
          thumbUpCount: 0,
          viewCount: 1,
          createTime: "약 1시간 전",
          edited: true,
          title: "",
          contents:
            "첫코 + 풀페이스 지방이식 \r\n지방이식이랑 코성형 같이 하려고 병원 알아보고 있어요 \r\n\r\n어나더 지승렬 원장님 예약해둬서 \r\n이번주 상담가는데 \r\n또 가볼만한 병원 추천 좀 해주세요 \r\n한곳은 넘 적다고 해서 한두곳만 더 가보려구요! \r\n\r\n#자려코 #화려코 #자려려코 #기증늑 #자가늑",
          photos: [
            {
              url: "https://image2.gnsister.com/images/document/1716943193094_8052a9e69e104bffaa51788763b353d3.jpg?originalImageWidth=527&originalImageHeight=558",
            },
          ],
          lang: "ko",
          hasDoctorComment: false,
          translateResult: null,
        },
        {
          id: 2718008,
          categoryId: 1,
          categoryName: "자유수다",
          writer: {
            id: 2497391,
            doctorId: null,
            profile:
              "https://image2.gnsister.com/images/member/profile/1513135488959_4131ffc481d74b849460ec1ea11fd9d5.png",
            nickname: "가짜코미녀",
            level: 5,
            engagementType: null,
          },
          writerDoctorId: null,
          hasThumbUp: false,
          commentCount: 5,
          thumbUpCount: 0,
          viewCount: 4,
          createTime: "약 3시간 전",
          edited: true,
          title: "",
          contents: "나 코성형 한지 2주일 됬는데 봐줄사람? 괜찮아?",
          photos: [
            {
              url: "https://image2.gnsister.com/images/document/1716936934696_7408bd06f6e44bb99876ec1473bc9f7c.jpg?originalImageWidth=1080&originalImageHeight=1440",
            },
          ],
          lang: "ko",
          hasDoctorComment: false,
          translateResult: null,
        },
      ],
      hospitals: [
        {
          id: 370,
          name: "팝성형외과의원",
          mainImage:
            "https://image2.gnsister.com/images/direct/1678167128052_6e4daae119b846e98ac9da648f98e5b9.jpg?originalImageWidth=600&originalImageHeight=240",
          rating: 9.4,
          ratingCount: 9974,
          reviewCount: 41042,
          supportingLangList: ["ja"],
          isCertified: false,
          assessmentState: "GROWTH",
          photos: [],
          sido: "서울",
          pageCount: 25,
        },
        {
          id: 938,
          name: "나나성형외과의원",
          mainImage:
            "https://image2.gnsister.com/images/direct/1677820120807_7329b9dcdc5746de8c5e01b9dbcc97bb.jpg?originalImageWidth=600&originalImageHeight=240",
          rating: 9.6,
          ratingCount: 15017,
          reviewCount: 39300,
          supportingLangList: ["ja"],
          isCertified: false,
          assessmentState: "GROWTH",
          photos: [],
          sido: "서울",
          pageCount: 72,
        },
        {
          id: 250,
          name: "디에이성형외과의원",
          mainImage:
            "https://image2.gnsister.com/images/hospital/1515034360262_edcd481595034a08a0190a2c3cf7a517.jpg",
          rating: 9.4,
          ratingCount: 8788,
          reviewCount: 32431,
          supportingLangList: ["ja"],
          isCertified: false,
          assessmentState: "GROWTH",
          photos: [],
          sido: "서울",
          pageCount: 81,
        },
      ],
      treatments: [],
      language: "ko-KR",
      token: "fd5ec22e099a45c0a9894c2e4e22007d",
      blogs: null,
      blogTotalLength: null,
      title: "'코성형'에 대한 검색결과 23442개 | 강남언니",
      meta: {
        description:
          "국내 1위 성형정보앱 강남언니. 리얼후기부터 가격비교, 상담예약까지 한번에. 강남언니를 지금 만나보세요.",
        image: "https://www.gangnamunni.com/images/kr/meta_thumb_02.jpg",
        locale: "ko_KR",
        name: "강남언니",
        title: "'코성형'에 대한 검색결과 23442개 | 강남언니",
        twtCardType: "summary_large_image",
        type: "website",
        desc: "'코성형'을 전문으로 하는 병원과 이벤트를 확인해보세요!",
      },
    },
    __N_SSP: true,
  },
];
